// The P1 action catalog of P1 contract §5.2, as data for tests/contracts/actions.test.ts: type, owning section, the
// reveals / commits flags (a conditional commit, `C if …`, is false here: the handler marks it), the error codes beyond
// the framework's and the warning codes. `prospect/modifyProgram` also returns the create codes and warnings.
export interface ContractActionRow {
  type: string;
  section: number;
  reveals: boolean;
  commits: boolean;
  errors: readonly string[];
  warnings: readonly string[];
}

export const CONTRACT_ACTIONS: readonly ContractActionRow[] = [
  {
    type: 'owner/setAssignment',
    section: 1,
    reveals: false,
    commits: false,
    errors: [
      'CLAIM_NOT_ACTIVE',
      'ASSIGNMENT_INVALID',
      'ROLE_NOT_AVAILABLE',
      'PROGRAM_NOT_ACTIVE',
      'MACHINE_NOT_ON_CLAIM',
      'OWNER_INJURED',
      'FOREMAN_SLOT_TAKEN',
    ],
    warnings: ['SMALL_CREW_ENDS'],
  },
  {
    type: 'owner/setSalary',
    section: 1,
    reveals: false,
    commits: false,
    errors: ['NEGATIVE_AMOUNT', 'ABOVE_CAP_INVESTOR', 'DISTRESS_BLOCKED'],
    warnings: [],
  },
  {
    type: 'owner/draw',
    section: 1,
    reveals: false,
    commits: false,
    errors: ['NEGATIVE_AMOUNT', 'INSUFFICIENT_FUNDS', 'DISTRESS_BLOCKED'],
    warnings: [],
  },
  {
    type: 'owner/inject',
    section: 1,
    reveals: false,
    commits: false,
    errors: ['NEGATIVE_AMOUNT', 'INSUFFICIENT_PERSONAL_CASH', 'EQUITY_LOCKED'],
    warnings: [],
  },
  {
    type: 'community/sponsor',
    section: 1,
    reveals: false,
    commits: true,
    errors: ['BELOW_MINIMUM', 'CAP_REACHED', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  { type: 'game/retire', section: 1, reveals: false, commits: true, errors: ['SCENARIO_ACTIVE'], warnings: [] },
  {
    type: 'world/siteVisit',
    section: 3,
    reveals: false,
    commits: false,
    errors: ['CLAIM_UNKNOWN', 'ACCESS_CLOSED', 'OWNER_INJURED', 'VISIT_ALREADY_BOOKED', 'INSUFFICIENT_FUNDS'],
    warnings: ['DESK_DAYS_QUEUED'],
  },
  {
    type: 'world/setWatch',
    section: 3,
    reveals: false,
    commits: false,
    errors: ['UNKNOWN_TARGET', 'WATCH_LIMIT'],
    warnings: [],
  },
  {
    type: 'prospect/panSurvey',
    section: 4,
    reveals: false,
    commits: false,
    errors: [
      'NO_ACCESS',
      'NOT_IN_SEASON',
      'ACCESS_CLOSED',
      'OWNER_INJURED',
      'VISIT_ALREADY_BOOKED',
      'CREW_UNAVAILABLE',
      'INSUFFICIENT_FUNDS',
    ],
    warnings: ['DESK_DAYS_QUEUED'],
  },
  {
    type: 'prospect/createProgram',
    section: 4,
    reveals: false,
    commits: false,
    errors: [
      'NO_ACCESS',
      'METHOD_NOT_AVAILABLE',
      'MACHINE_UNSUITABLE',
      'MACHINE_NOT_ON_CLAIM',
      'CREW_UNAVAILABLE',
      'GEOLOGIST_REQUIRED',
      'GEOLOGIST_AT_CAPACITY',
      'INVALID_TARGET',
      'BLOCK_BEING_MINED',
    ],
    warnings: ['NOT_IN_SEASON', 'PERMIT_REQUIRED'],
  },
  {
    type: 'prospect/modifyProgram',
    section: 4,
    reveals: false,
    commits: false,
    errors: ['PROGRAM_NOT_FOUND', 'PROGRAM_CLOSED'],
    warnings: [],
  },
  {
    type: 'prospect/pauseProgram',
    section: 4,
    reveals: false,
    commits: false,
    errors: ['PROGRAM_NOT_FOUND', 'PROGRAM_CLOSED'],
    warnings: [],
  },
  {
    type: 'prospect/resumeProgram',
    section: 4,
    reveals: false,
    commits: false,
    errors: ['PROGRAM_NOT_FOUND', 'PROGRAM_CLOSED'],
    warnings: [],
  },
  {
    type: 'prospect/cancelProgram',
    section: 4,
    reveals: false,
    commits: false,
    errors: ['PROGRAM_NOT_FOUND', 'PROGRAM_CLOSED'],
    warnings: [],
  },
  {
    type: 'prospect/bookContractor',
    section: 4,
    reveals: false,
    commits: true,
    errors: ['NO_RIG_AVAILABLE', 'METHOD_NOT_AVAILABLE', 'PROGRAM_NOT_FOUND', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'prospect/recordsReview',
    section: 4,
    reveals: false,
    commits: false,
    errors: ['REVIEW_IN_PROGRESS', 'GEOLOGIST_AT_CAPACITY', 'INVALID_TARGET', 'INSUFFICIENT_FUNDS'],
    warnings: ['DESK_DAYS_QUEUED'],
  },
  {
    type: 'prospect/engageConsultant',
    section: 4,
    reveals: false,
    commits: true,
    errors: ['CONSULTANT_UNAVAILABLE', 'INVALID_TARGET', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  { type: 'prospect/setPlanning', section: 4, reveals: false, commits: false, errors: ['INVALID_VALUE'], warnings: [] },
  {
    type: 'land/acceptAsk',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['LISTING_NOT_OPEN', 'STRUCTURE_NOT_OFFERED', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'land/buyDownRoyalty',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['NO_BUYDOWN_CLAUSE', 'BUYDOWN_FLOOR', 'IN_DEFAULT', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'land/exerciseOption',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['TENURE_NOT_FOUND', 'NO_OPTION', 'OPTION_EXPIRED', 'IN_DEFAULT', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'land/setLeaseRenewal',
    section: 5,
    reveals: false,
    commits: false,
    errors: ['TENURE_NOT_FOUND', 'NO_RENEWAL_RIGHT', 'IN_DEFAULT'],
    warnings: ['RENEWAL_OPT_OUT_SITE_ACTIVE'],
  },
  {
    type: 'land/surrenderLease',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['TENURE_NOT_FOUND', 'NOT_LEASED', 'SURRENDER_PENDING', 'SITE_ACTIVE'],
    warnings: [],
  },
  {
    type: 'land/quickSell',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['TENURE_NOT_FOUND', 'TENURE_NOT_OWNED', 'QUICK_SALE_PENDING', 'SITE_ACTIVE'],
    warnings: [],
  },
  {
    type: 'land/relinquish',
    section: 5,
    reveals: false,
    commits: true,
    errors: ['TENURE_NOT_FOUND', 'TENURE_CANNOT_RELINQUISH', 'SITE_ACTIVE'],
    warnings: [],
  },
  {
    type: 'permits/payObligation',
    section: 6,
    reveals: false,
    commits: false,
    errors: ['OBLIGATION_NOT_FOUND', 'OBLIGATION_NOT_OPEN', 'NOT_PAYABLE', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'permits/payObligations',
    section: 6,
    reveals: false,
    commits: false,
    errors: ['EMPTY_BATCH', 'OBLIGATION_NOT_FOUND'],
    warnings: ['BATCH_PARTIAL'],
  },
  {
    type: 'permits/setAutoPay',
    section: 6,
    reveals: false,
    commits: false,
    errors: ['OBLIGATION_NOT_FOUND', 'NOT_AUTOPAY_ELIGIBLE'],
    warnings: [],
  },
  {
    type: 'ops/setMinePlan',
    section: 7,
    reveals: false,
    commits: false,
    errors: [
      'CLAIM_NOT_HELD',
      'FOREMAN_REQUIRED',
      'LINE_LIMIT',
      'LINE_INVALID',
      'BLOCK_NOT_IN_CLAIM',
      'CUT_NOT_CONTIGUOUS',
      'CUT_EMPTY',
      'BLOCK_RECLAIMED',
      'BLOCK_OCCUPIED',
      'BLOCK_EXCLUDED',
      'MACHINE_NOT_ON_CLAIM',
      'ASSET_DOUBLE_BOOKED',
      'ROLE_INCOMPATIBLE',
      'EMPLOYEE_NOT_AVAILABLE',
      'SCHEDULE_INVALID',
      'FEED_TARGET_TOO_HIGH',
      'PLANT_NO_FEED',
      'BULK_SAMPLE_LIMIT',
      'LINE_NEEDS_PLANT_OPERATOR',
    ],
    warnings: [
      'TRUCKS_UNDERMATCHED',
      'WATER_SHORT',
      'POWER_SHORT',
      'FUEL_SHORT',
      'ONE_PLANT_OPERATOR_TWO_SHIFTS',
      'STRIP_BELOW_NEED',
      'PILE_STRIPPED_AS_WASTE',
      'SMALL_CREW_NO_FOREMAN',
      'FIELD_IGNORED_THIS_PHASE',
      'LINE_LEAD_HAND',
    ],
  },
  {
    type: 'ops/setPlanActive',
    section: 7,
    reveals: false,
    commits: false,
    errors: ['CLAIM_NOT_HELD', 'SITE_NOT_READY', 'FOREMAN_REQUIRED', 'CUT_EMPTY'],
    warnings: [],
  },
  {
    type: 'ops/cleanupNow',
    section: 7,
    reveals: false,
    commits: false,
    errors: ['NO_PLANT', 'SITE_NOT_RUNNING', 'LINE_INVALID'],
    warnings: [],
  },
  {
    type: 'ops/movePlant',
    section: 7,
    reveals: false,
    commits: false,
    errors: ['BLOCK_NOT_IN_CLAIM', 'BLOCK_OCCUPIED', 'BLOCK_EXCLUDED', 'LINE_INVALID'],
    warnings: ['PAY_UNDER_PLANT_SITE'],
  },
  {
    type: 'ops/mobilizeSite',
    section: 7,
    reveals: false,
    commits: true,
    errors: ['CLAIM_NOT_HELD', 'SITE_EXISTS', 'ACCESS_CLOSED', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  { type: 'ops/winterize', section: 7, reveals: false, commits: false, errors: ['SITE_NOT_RUNNING'], warnings: [] },
  {
    type: 'ops/startup',
    section: 7,
    reveals: false,
    commits: false,
    errors: ['SITE_NOT_WINTERIZED', 'NO_CREW_ON_SITE'],
    warnings: [],
  },
  {
    type: 'ops/demobilizeSite',
    section: 7,
    reveals: false,
    commits: true,
    errors: ['SITE_NOT_READY', 'ACCESS_CLOSED'],
    warnings: ['MACHINES_ON_SITE'],
  },
  {
    type: 'ops/drillWell',
    section: 7,
    reveals: false,
    commits: true,
    errors: ['SITE_NOT_READY', 'WELL_LIMIT', 'NOT_ARID', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'ops/tailingsAudit',
    section: 7,
    reveals: true,
    commits: true,
    errors: ['NO_PLANT_OPERATOR', 'LINE_INVALID', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'staff/hire',
    section: 8,
    reveals: false,
    commits: true,
    errors: [
      'CANDIDATE_GONE',
      'ROLE_NOT_ELIGIBLE',
      'START_TOO_SOON',
      'PAY_BELOW_ASK',
      'BELOW_MIN_WAGE',
      'SALARY_NOT_EXEMPT',
      'ASSIGNMENT_INVALID',
      'ROLE_INCOMPATIBLE',
    ],
    warnings: ['CAMP_FULL', 'SMALL_CREW_ENDS'],
  },
  {
    type: 'staff/cancelHire',
    section: 8,
    reveals: false,
    commits: true,
    errors: ['EMPLOYEE_NOT_FOUND', 'NOT_PENDING'],
    warnings: [],
  },
  {
    type: 'staff/useRecruiter',
    section: 8,
    reveals: false,
    commits: true,
    errors: ['ROLE_NOT_ELIGIBLE', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'staff/assign',
    section: 8,
    reveals: false,
    commits: false,
    errors: [
      'EMPLOYEE_NOT_FOUND',
      'EMPLOYEE_NOT_AVAILABLE',
      'ROLE_INCOMPATIBLE',
      'FOREMAN_SLOT_TAKEN',
      'COVERAGE_ROLE_ONLY',
      'ASSIGNMENT_INVALID',
    ],
    warnings: ['SMALL_CREW_ENDS', 'CAMP_FULL'],
  },
  {
    type: 'staff/setPay',
    section: 8,
    reveals: false,
    commits: false,
    errors: ['EMPLOYEE_NOT_FOUND', 'BELOW_MIN_WAGE', 'SALARY_NOT_EXEMPT'],
    warnings: [],
  },
  {
    type: 'staff/giveBonus',
    section: 8,
    reveals: false,
    commits: false,
    errors: ['EMPLOYEE_NOT_FOUND', 'NEGATIVE_AMOUNT', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'staff/fire',
    section: 8,
    reveals: false,
    commits: true,
    errors: ['EMPLOYEE_NOT_FOUND', 'CAUSE_NOT_DOCUMENTED'],
    warnings: [],
  },
  {
    type: 'staff/layoff',
    section: 8,
    reveals: false,
    commits: true,
    errors: ['EMPLOYEE_NOT_FOUND', 'EMPLOYEE_NOT_AVAILABLE'],
    warnings: [],
  },
  {
    type: 'staff/recall',
    section: 8,
    reveals: false,
    commits: true,
    errors: ['NOT_ON_RECALL_LIST', 'START_TOO_SOON'],
    warnings: ['SMALL_CREW_ENDS'],
  },
  {
    type: 'fleet/buy',
    section: 9,
    reveals: false,
    commits: true,
    errors: [
      'LISTING_GONE',
      'NOT_FOR_SALE',
      'DESTINATION_INVALID',
      'OPTION_INVALID',
      'ACCESS_CLOSED',
      'INSUFFICIENT_FUNDS',
    ],
    warnings: ['TRANSPORT_WINDOW_RISK', 'TRANSPORT_UNFUNDED'],
  },
  {
    type: 'fleet/move',
    section: 9,
    reveals: false,
    commits: true,
    errors: ['MACHINE_NOT_FOUND', 'MACHINE_IN_TRANSIT', 'DESTINATION_INVALID', 'ACCESS_CLOSED', 'INSUFFICIENT_FUNDS'],
    warnings: ['TRANSPORT_WINDOW_RISK', 'MACHINE_IN_PLAN'],
  },
  {
    type: 'fleet/sell',
    section: 9,
    reveals: false,
    commits: true,
    errors: ['MACHINE_NOT_FOUND', 'MACHINE_IN_TRANSIT'],
    warnings: ['MACHINE_IN_PLAN'],
  },
  {
    type: 'gold/sellLocal',
    section: 10,
    reveals: false,
    commits: true,
    errors: ['LOT_NOT_HELD', 'BUYER_NOT_IN_DISTRICT', 'AMOUNT_INVALID'],
    warnings: [],
  },
  {
    type: 'gold/setStandingOrder',
    section: 10,
    reveals: false,
    commits: false,
    errors: ['BUYER_NOT_FOUND', 'REFINERY_NOT_AVAILABLE', 'AMOUNT_INVALID'],
    warnings: [],
  },
  {
    type: 'finance/payBill',
    section: 11,
    reveals: false,
    commits: false,
    errors: ['BILL_NOT_FOUND', 'AMOUNT_INVALID', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
  {
    type: 'finance/prepay',
    section: 11,
    reveals: false,
    commits: false,
    errors: ['LOAN_CLOSED', 'AMOUNT_INVALID', 'INSUFFICIENT_FUNDS'],
    warnings: [],
  },
];
