// geology.estSmallCountTable (DESIGN §4.4.4): mean b and variance v of t = ln(max(M, 0.5 μ*) / E[M]) for the
// non-coarse composite mass M of a sample holding N_eff effective particles. GENERATED by
// `npx tsx sim/calibration/estimator-smalltab.ts` from §3's engine drawSample (mid-reach non-coarse shares, full
// capture, no measurement or local noise, 400000 draws per point); regenerate whenever §3 changes particle masses
// or CVs. Above the last grid point the estimator uses the lognormal limit b = −½ ln(1 + 1/N), v = ln(1 + 1/N).
export const smallCountTable = [
  { n: 0.03, b: 2.8217, v: 0.0096 },
  { n: 0.1, b: 1.639, v: 0.0337 },
  { n: 0.3, b: 0.6134, v: 0.113 },
  { n: 0.5, b: 0.1898, v: 0.1984 },
  { n: 1, b: -0.2044, v: 0.3801 },
  { n: 2, b: -0.1847, v: 0.34 },
  { n: 3, b: -0.134, v: 0.2544 },
  { n: 5, b: -0.0873, v: 0.1692 },
  { n: 10, b: -0.0469, v: 0.0914 },
  { n: 20, b: -0.0238, v: 0.0475 },
  { n: 50, b: -0.01, v: 0.0196 },
] as const;
