// geology.estSmallCountTable (DESIGN §4.4.4): mean b and variance v of t = ln(max(M, 0.5 μ*) / E[M]) for the
// non-coarse composite mass M of a sample holding N_eff effective particles. GENERATED by
// `npx tsx sim/calibration/estimator-smalltab.ts` from §3's engine drawSample (mid-reach non-coarse shares, full
// capture, no measurement or local noise); regenerate whenever §3 changes particle masses or CVs. Above the last grid
// point the estimator uses the lognormal limit b = −½ ln(1 + 1/N), v = ln(1 + 1/N).
export const smallCountTable = [
  { n: 0.03, b: 2.8228, v: 0.0111 },
  { n: 0.1, b: 1.6399, v: 0.035 },
  { n: 0.3, b: 0.6115, v: 0.1107 },
  { n: 0.5, b: 0.1913, v: 0.1982 },
  { n: 1, b: -0.2009, v: 0.3833 },
  { n: 2, b: -0.182, v: 0.3402 },
  { n: 3, b: -0.1329, v: 0.2518 },
  { n: 5, b: -0.0847, v: 0.1691 },
  { n: 10, b: -0.046, v: 0.0916 },
  { n: 20, b: -0.0233, v: 0.0478 },
  { n: 50, b: -0.0099, v: 0.0198 },
] as const;
