// `npx tsx sim/calibration/estimator-smalltab.ts [--draws N] [--check]` regenerates geology.estSmallCountTable
// (DESIGN §4.4.4) from §3's ENGINE drawSample: a block whose whole pay column is sampled (no de Wijs term), full
// capture and no measurement noise, non-coarse gold only at the mid-reach shares, and the grade set so the sample
// holds N_eff effective particles. For each grid point it records the mean b and variance v of
// t = ln(max(M, ½μ*) / E[M]). Deterministic (one 'sample' stream per grid point). Writes
// src/data/prospecting/smallCountTable.ts and prints the prototype's table beside it as a cross-check; --check only
// prints.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { baseTuning } from '../../src/data/tuning';
import { rng } from '../../src/engine/core/rng';
import { log } from '../../src/engine/core/dmath';
import { snapshotGenParams } from '../../src/engine/systems/world';
import { BCY_PER_ACRE_FT, MG_PER_OZ } from '../../src/engine/systems/world/constants';
import { UNTOUCHED_BLOCK, drawSample } from '../../src/engine/systems/world/sample';
import type { BlockTruth, SampleMethodParams } from '../../src/engine/systems/world/types';

export const SMALLTAB_GRID = [0.03, 0.1, 0.3, 0.5, 1, 2, 3, 5, 10, 20, 50] as const;

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

export interface SmallTabRow {
  readonly n: number;
  readonly b: number;
  readonly v: number;
}

export function generateSmallCountTable(draws: number): SmallTabRow[] {
  const gp = snapshotGenParams(baseTuning, []);
  const phys = gp.sample;
  // Mid-reach non-coarse shares (§3.2 north midReach 25/40/27/8 without the coarse class).
  const nc = [0.4, 0.27, 0.08];
  const tot = nc[0]! + nc[1]! + nc[2]!;
  const share = nc.map((x) => x / tot);
  const mu = phys.particleMeanMg;
  const cv = phys.massCv;
  let muStar = 0;
  for (let c = 0; c < 3; c++) muStar += share[c]! * mu[c]! * (1 + cv[c + 1]! * cv[c + 1]!);
  const T = 5;
  const V = T * BCY_PER_ACRE_FT; // V = Vb: no local (de Wijs) term
  const method: SampleMethodParams = {
    id: 'smalltab',
    positionMode: 'fullColumn',
    maxDepthFt: null,
    frozenOk: true,
    bedrockPenFt: 0,
    captureBySize: { coarse: 1, medium: 1, fine: 1, ultrafine: 1 },
    volumeCv: 0,
    weighCv: 0,
    geomCv: 0,
    thickCv: 0,
    biasMult: 1,
    reportsClassMasses: true,
  };
  const ctx = { surface: 'u' as const, climateBand: 'subarctic' as const, physics: phys };
  const rows: SmallTabRow[] = [];
  SMALLTAB_GRID.forEach((nEff, gi) => {
    const EM = nEff * muStar;
    const g = EM / (V * MG_PER_OZ);
    const bt: BlockTruth = {
      overburdenFt: 0,
      payThicknessFt: T,
      bedrockCleanupFt: 0,
      gradeOzPerBcy: g,
      virginGradeOzPerBcy: g,
      sizeMix: { coarse: 0, medium: share[0]!, fine: share[1]!, ultrafine: share[2]! },
      coarseMeanMg: 150,
      fineness: 0.86,
      permafrost: 0,
      clay: 0,
      boulders: 0,
      cementation: 0,
      bedrockType: 'schist',
      bedrockGoldShare: 0,
      verticalDecayFt: 2,
      paystreakFraction: 1,
      minedOutFraction: 0,
    };
    const r = rng('smalltab', 'sample', 'smalltab', gi);
    let s1 = 0;
    let s2 = 0;
    for (let t = 0; t < draws; t++) {
      const res = drawSample(bt, UNTOUCHED_BLOCK, { blockId: 'blk_000001' as never, volumeBcy: V }, method, r, ctx);
      const x = log(Math.max(res.recoveredMg, 0.5 * muStar) / EM);
      s1 += x;
      s2 += x * x;
    }
    const m = s1 / draws;
    rows.push({ n: nEff, b: Math.round(m * 1e4) / 1e4, v: Math.round((s2 / draws - m * m) * 1e4) / 1e4 });
  });
  return rows;
}

function main(): void {
  const draws = Number(arg('draws') ?? 100000);
  const rows = generateSmallCountTable(draws);
  const proto = JSON.parse(
    readFileSync(new URL('../../docs/prototypes/estimator/smalltab.json', import.meta.url), 'utf8'),
  ) as SmallTabRow[];
  console.log(`Small-count table from §3's engine drawSample (${draws} draws per point); prototype in brackets`);
  for (const r of rows) {
    const p = proto.find((x) => x.n === r.n);
    console.log(
      `  N_eff ${String(r.n).padStart(5)}  b ${r.b.toFixed(4).padStart(8)} [${p?.b.toFixed(4) ?? '—'}]  v ${r.v.toFixed(4)} [${p?.v.toFixed(4) ?? '—'}]  lognormal b ${(-0.5 * Math.log(1 + 1 / r.n)).toFixed(4)} v ${Math.log(1 + 1 / r.n).toFixed(4)}`,
    );
  }
  if (process.argv.includes('--check')) return;
  const body = rows.map((r) => `  { n: ${r.n}, b: ${r.b}, v: ${r.v} },`).join('\n');
  const file = `// geology.estSmallCountTable (DESIGN §4.4.4): mean b and variance v of t = ln(max(M, 0.5 μ*) / E[M]) for the
// non-coarse composite mass M of a sample holding N_eff effective particles. GENERATED by
// \`npx tsx sim/calibration/estimator-smalltab.ts\` from §3's engine drawSample (mid-reach non-coarse shares, full
// capture, no measurement or local noise, ${draws} draws per point); regenerate whenever §3 changes particle masses
// or CVs. Above the last grid point the estimator uses the lognormal limit b = −½ ln(1 + 1/N), v = ln(1 + 1/N).
export const smallCountTable = [
${body}
] as const;
`;
  writeFileSync(new URL('../../src/data/prospecting/smallCountTable.ts', import.meta.url), file);
  console.log('wrote src/data/prospecting/smallCountTable.ts');
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) main();
