// Fixture loaders for UI tests (DESIGN §13.27 "Ownership and fixtures in P1"; S13-10). The committed P1 fixtures are
// `.gmt.json.gz` saves (`tests/fixtures/make-p1-midgame.ts`, `make-p1-year10.ts`, generated by `ui-gates`); a test
// reads the file's bytes (node:fs is a test-file privilege) and hands them here, and the save goes through the same
// reader the Saves screen's import uses, so a fixture loads exactly as a player's file would.
import { saveCodec, type SaveFile } from '../../engine';
import { readSave, type SaveNotice } from '../../persistence';
import type { Harness } from './harness';

/** The engine SaveFile in `bytes` (gzip or plain JSON), with the reader's notices; throws with the reader's message. */
export function saveFromBytes(bytes: Uint8Array | string): {
  readonly save: SaveFile;
  readonly notices: readonly SaveNotice[];
} {
  const read = readSave(bytes, saveCodec);
  if (!read.ok) throw new Error(`fixture save could not be read: ${read.error.code}: ${read.error.message}`);
  return { save: read.value.save as SaveFile, notices: read.value.notices };
}

/** Loads a fixture save into the harness's client, as `ui/import` then `ui/load` would. */
export function loadFixtureSave(harness: Harness, bytes: Uint8Array | string): SaveFile {
  const { save } = saveFromBytes(bytes);
  harness.client.load(save);
  return save;
}
